TEENSY = 36
INO_FILES = HTTPS_Connect.ino

TEENSY_LIBS += Entropy Time SPI EEPROM

LIB_DIRS += /Volumes/Devel/crypto/WolfSSLClient

LIB_DIRS += /Volumes/Devel/Arduino/WiFi101/src

LIB_INCLUDE += . 

EXTRA_DEFINES += CORE_TEENSY
include /Volumes/Devel/teensy/teensy.mk

